package com.jooyer.jooyerretrofit.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jooyer.jooyerretrofit.retrofit.bean.CookieBean;
import com.jooyer.jooyerretrofit.retrofit.bean.DownBean;

import com.jooyer.jooyerretrofit.dao.CookieBeanDao;
import com.jooyer.jooyerretrofit.dao.DownBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cookieBeanDaoConfig;
    private final DaoConfig downBeanDaoConfig;

    private final CookieBeanDao cookieBeanDao;
    private final DownBeanDao downBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cookieBeanDaoConfig = daoConfigMap.get(CookieBeanDao.class).clone();
        cookieBeanDaoConfig.initIdentityScope(type);

        downBeanDaoConfig = daoConfigMap.get(DownBeanDao.class).clone();
        downBeanDaoConfig.initIdentityScope(type);

        cookieBeanDao = new CookieBeanDao(cookieBeanDaoConfig, this);
        downBeanDao = new DownBeanDao(downBeanDaoConfig, this);

        registerDao(CookieBean.class, cookieBeanDao);
        registerDao(DownBean.class, downBeanDao);
    }
    
    public void clear() {
        cookieBeanDaoConfig.clearIdentityScope();
        downBeanDaoConfig.clearIdentityScope();
    }

    public CookieBeanDao getCookieBeanDao() {
        return cookieBeanDao;
    }

    public DownBeanDao getDownBeanDao() {
        return downBeanDao;
    }

}
